"""
Memory package.
Memoria del estudiante, sesión y cache.
"""

from backend.memory.student_profile import (
    ProficiencyLevel,
    LearningStyle,
    ConceptMastery,
    StudentProfile,
    load_profile,
    create_profile,
    update_profile,
    infer_weaknesses,
    get_recommended_concepts,
    get_level_config,
)

from backend.memory.session_memory import (
    TurnRole,
    TurnType,
    ConversationTurn,
    SessionContext,
    store_turn,
    get_recent_context,
    get_context_for_llm,
    get_related_turns,
    get_active_concepts,
    prune_context,
    summarize_and_prune,
    get_session_stats,
    export_session,
    import_session,
    clear_session,
    clear_all_sessions,
)

from backend.memory.cache import (
    CacheStrategy,
    CacheEntry,
    CacheStats,
    CacheManager,
    get_cached_answer,
    store_cache,
    invalidate_cache,
    get_cached_embedding,
    store_embedding,
    get_cached_chunk,
    store_chunk,
    invalidate_chunks_by_document,
    get_cache_stats,
    clear_all_caches,
    reset_caches,
    cached,
)

__all__ = [
    # student_profile
    "ProficiencyLevel",
    "LearningStyle",
    "ConceptMastery",
    "StudentProfile",
    "load_profile",
    "create_profile",
    "update_profile",
    "infer_weaknesses",
    "get_recommended_concepts",
    "get_level_config",
    # session_memory
    "TurnRole",
    "TurnType",
    "ConversationTurn",
    "SessionContext",
    "store_turn",
    "get_recent_context",
    "get_context_for_llm",
    "get_related_turns",
    "get_active_concepts",
    "prune_context",
    "summarize_and_prune",
    "get_session_stats",
    "export_session",
    "import_session",
    "clear_session",
    "clear_all_sessions",
    # cache
    "CacheStrategy",
    "CacheEntry",
    "CacheStats",
    "CacheManager",
    "get_cached_answer",
    "store_cache",
    "invalidate_cache",
    "get_cached_embedding",
    "store_embedding",
    "get_cached_chunk",
    "store_chunk",
    "invalidate_chunks_by_document",
    "get_cache_stats",
    "clear_all_caches",
    "reset_caches",
    "cached",
]
