"""
Graph package (GraphRAG).
Schema, builders y traversal del grafo de conocimiento.
"""

from backend.graph.schema import (
    NodeType,
    EdgeType,
    BaseNode,
    ConceptNode,
    TopicNode,
    ChunkNode,
    SourceNode,
    DefinitionNode,
    Edge,
    define_nodes,
    define_edges,
    validate_node,
    validate_edge,
    validate_graph,
    get_schema_queries,
)

from backend.graph.builders import (
    create_node,
    create_concept_node,
    create_topic_node,
    create_chunk_node,
    create_source_node,
    create_definition_node,
    create_edge,
    link_concepts,
    attach_evidence,
    link_chunk_to_source,
    link_parent_child_chunks,
    add_concept_to_topic,
    update_node,
    update_concept_embedding,
    update_chunk_embedding,
    update_edge_weight,
    delete_node,
    delete_edge,
    batch_create_concepts,
    batch_create_chunks,
    batch_link_concepts,
)

__all__ = [
    # Schema
    "NodeType",
    "EdgeType",
    "BaseNode",
    "ConceptNode",
    "TopicNode",
    "ChunkNode",
    "SourceNode",
    "DefinitionNode",
    "Edge",
    "define_nodes",
    "define_edges",
    "validate_node",
    "validate_edge",
    "validate_graph",
    "get_schema_queries",
    # Builders
    "create_node",
    "create_concept_node",
    "create_topic_node",
    "create_chunk_node",
    "create_source_node",
    "create_definition_node",
    "create_edge",
    "link_concepts",
    "attach_evidence",
    "link_chunk_to_source",
    "link_parent_child_chunks",
    "add_concept_to_topic",
    "update_node",
    "update_concept_embedding",
    "update_chunk_embedding",
    "update_edge_weight",
    "delete_node",
    "delete_edge",
    "batch_create_concepts",
    "batch_create_chunks",
    "batch_link_concepts",
]
